### ISSUE TITLE
Algorithms used in top performance WMT Systems

### ISSUE THREAD

**Issue by MarkWuNLP** [THUNLP-MT/MT-Reading-List#11]
Thank you for your awesome MT-Reading-List. I suggest adding algorithms used in top performance WMT systems, because some papers are just papers which are not effective when data are abundant. Furthermore, an ensemble Transformer + BPE + Back-translation is a strong baseline in practice. The algorithms employed in WMT competitions will clarify which idea actually works when data are abundant.

**Comment by minicheshire** [comment]
Hi! You've made the point. We'll maintain a section about the techniques that really have a strong performance in practice. Thanks for your suggestions!
