### ISSUE TITLE
WMT 2018 paper on Multilingual Translation

### ISSUE THREAD

**Issue by DevSinghSachan** [THUNLP-MT/MT-Reading-List#12]
Hello,
Very nice list of papers covering a range of topics related to modern MT techniques.
I thought the below paper would be a good addition to the multilingual MT models.

Parameter Sharing Methods for Multilingual Self-Attentional Translation Models
http://aclweb.org/anthology/W18-6327

Best,

**Comment by minicheshire** [comment]
Hi, thanks for your recommendation! We've added it to the list~ 
Happy New Year!
