### ISSUE TITLE
A robust self-learning method for fully unsupervised cross-lingual mappings of word embeddings

### ISSUE THREAD

**Issue by muyeby** [THUNLP-MT/MT-Reading-List#14]
ACL 2018
pdf: http://aclweb.org/anthology/P18-1073
intro: This paper introduced a robust self-learning method to learn an unsupervised bilingual word mapping, and use it to induce bilingual lexicons. They claimed state-of-the-art results on the dataset of Dinu et al. (2015) and the extensions of Artetxe et al. (2017, 2018a)

**Comment by minicheshire** [comment]
Hi, thanks for your recommendation! I've added the paper (and several related ones) to the list~
