### ISSUE TITLE
A paper might be Inappropriately categorized

### ISSUE THREAD

**Issue by zhengzx-nlp** [THUNLP-MT/MT-Reading-List#26]
Zhaopeng Tu, Yang Liu, Zhengdong Lu, Xiaohua Liu, and Hang Li. 2017. Context Gates for Neural Machine Translation. Transactions of the Association for Computational Linguistics. (Citation: 36)

This paper is essentially about how to balance source-side and target-side context in sentence-level MT. The paper might be inappropriately categorized into "document-level translation".

I personally suggest it could be put into "Coverage Constraints".

**Comment by minicheshire** [comment]
You're right. Thanks for pointing out!

**Comment by zhengzx-nlp** [comment]
Heihei.
