### ISSUE TITLE
SMT > Tutorials > Adam Lopez. 2008. Statistical Machine Translation link not working

### ISSUE THREAD

**Issue by nikola126** [THUNLP-MT/MT-Reading-List#28]
The link leading to Adam Lopez's paper Statistical Machine Translation is not working.

SMT > Tutorials > Adam Lopez. 2008. Statistical Machine Translation

**Comment by alvations** [comment]
Here's one copy of it http://kanagawa.lti.cs.cmu.edu/11780/sites/default/files/survey-staistical-machine-translation_0.pdf 

Related is a survey he did one year before https://apps.dtic.mil/dtic/tr/fulltext/u2/a466330.pdf
