### ISSUE TITLE
Neural machine translation with reconstruction

### ISSUE THREAD

**Issue by PolarLion** [THUNLP-MT/MT-Reading-List#31]
@inproceedings{tu2017neural,
  title={Neural machine translation with reconstruction},
  author={Tu, Zhaopeng and Liu, Yang and Shang, Lifeng and Liu, Xiaohua and Li, Hang},
  booktitle={Thirty-First AAAI Conference on Artificial Intelligence},
  year={2017}
}

**Comment by minicheshire** [comment]
Hi, thanks for your recommendation! I've added it to the section of *Model Architecture*~
