### ISSUE TITLE
Typos of Author Names

### ISSUE THREAD

**Issue by ustctf** [THUNLP-MT/MT-Reading-List#32]
**Yiming Wang**, Fei Tian, **Dongjian He**, Tao Qin, ChengXiang Zhai, Tie-Yan Liu. 2019. Non-Autoregressive Machine Translation with Auxiliary Regularization. In Proceedings of AAAI 2019.

The first and third authors have wrong names.

----------------------------------->

**Yiren Wang**, Fei Tian, **Di He**, Tao Qin, ChengXiang Zhai, Tie-Yan Liu. 2019. Non-Autoregressive Machine Translation with Auxiliary Regularization. In Proceedings of AAAI 2019.

**Comment by minicheshire** [comment]
Oops...! Thanks for pointing out!

**Comment by ustctf** [comment]
Thanks for addressing and listing our paper! :)
