### ISSUE TITLE
Improving Attention Modeling with Implicit Distortion and Fertility for Machine Translation

### ISSUE THREAD

**Issue by PolarLion** [THUNLP-MT/MT-Reading-List#33]
@inproceedings{Feng2016Improving,
  author    = {Shi Feng and
               Shujie Liu and
               Nan Yang and
               Mu Li and
               Ming Zhou and
               Kenny Q. Zhu},
  title     = {Improving Attention Modeling with Implicit Distortion and Fertility for Machine Translation},
  booktitle = {{COLING} 2016, 26th International Conference on Computational Linguistics,
               Proceedings of the Conference: Technical Papers, December 11-16, 2016,
               Osaka, Japan},
  pages     = {3082--3092},
  year      = {2016},
}

**Comment by minicheshire** [comment]
Hi, thanks for your recommendation again!
