### ISSUE TITLE
"Dual Inference for Machine Learning" and “Dual Supervised Learning”

### ISSUE THREAD

**Issue by PolarLion** [THUNLP-MT/MT-Reading-List#34]
@inproceedings{xia2017dualsupervised,
title={Dual Supervised Learning.},
author={Xia, Yingce and Qin, Tao and Chen, Wei and Bian, Jiang and Yu, Nenghai and Liu, Tieyan},
journal={international conference on machine learning},
pages={3789--3798},
year={2017}}
 
@inproceedings{Xia2017DualInference,
  author    = {Yingce Xia and
               Jiang Bian and
               Tao Qin and
               Nenghai Yu and
               Tie{-}Yan Liu},
  title     = {Dual Inference for Machine Learning},
  booktitle = {Proceedings of the Twenty-Sixth International Joint Conference on
               Artificial Intelligence, {IJCAI} 2017, Melbourne, Australia, August
               19-25, 2017},
  pages     = {3112--3118},
  year      = {2017},
  crossref  = {DBLP:conf/ijcai/2017},
  url       = {https://doi.org/10.24963/ijcai.2017/434},
  doi       = {10.24963/ijcai.2017/434},
  timestamp = {Wed, 27 Jun 2018 12:24:11 +0200},
  biburl    = {https://dblp.org/rec/bib/conf/ijcai/XiaBQYL17},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}

**Comment by minicheshire** [comment]
Hi! Thanks for your recommendation again~ 

These two papers can be viewed as the follow-up work of 
* Di He, Yingce Xia, Tao Qin, Liwei Wang, Nenghai Yu, Tie-Yan Liu, Wei-Ying Ma. 2016. [Dual Learning for Machine Translation](https://papers.nips.cc/paper/6469-dual-learning-for-machine-translation.pdf). In *Proceedings of NIPS 2016*.

I'll add them!
