### ISSUE TITLE
Any papers relating to transliteration?

### ISSUE THREAD

**Issue by echan00** [THUNLP-MT/MT-Reading-List#35]
Particularly, I'm looking for papers relating to incorporating domain glossaries and improving accuracy/consistency of number translations in neural machine translation

**Comment by minicheshire** [comment]
Hi!

According to your description, I think you might want to have a look at the subsection [**Word/Phrase Constraints**](https://github.com/THUNLP-MT/MT-Reading-List#word_phrase_constraints). 

For example, the third paper in that subsection ([**Incorporating Discrete Translation Lexicons into Neural Machine Translation**](https://aclweb.org/anthology/D16-1162)) shows an example that in English-Japanese translation, the word *Tunisia* is translated into ノルウェー(noruue-) by mistake, while the correct translation should be チュニジア(chunisia). I think this can be viewed as the transliteration problem that you mentioned. 

In my opinion, we can alleviate such problem by incorporating domain glossaries (say some transliteration dictionaries), and this goes to [**Prior Knowledge Integration**](https://github.com/THUNLP-MT/MT-Reading-List#prior_knowledge_integration) => [**Word/Phrase Constraints**](https://github.com/THUNLP-MT/MT-Reading-List#word_phrase_constraints). And also, if you are also looking for some easily practical techniques, the *name entity translation* technique might be a good choice, which is used by the champion of WMT'17 ZH-EN task (see [**WMT 2017**](https://github.com/THUNLP-MT/MT-Reading-List#wmt17)). The technique is described in their [**system report**](https://www.aclweb.org/anthology/W17-4742), which might also be a good reference.

Hope this would help you!

**Comment by echan00** [comment]
Thanks @minicheshire, will look into these!

I'm also looking for literature to rectify incorrect translation of numbers..

```
127萬美元 | US $ 1,700,000
EUR490 | 450欧元
$523M | 523百万澳元
十点五十五分 | 10:15
08:25am | 上午八时正
nine hundred and fifty-five thousand | 九十五万
$9.71 Billion | 9.71亿元
```

**Comment by minicheshire** [comment]
Hi!

I think the problems that you mentioned can still be alleviated by the techniques proposed in [**Word/Phrase Constraints**](https://github.com/THUNLP-MT/MT-Reading-List#word_phrase_constraints); You may also refer to [**CopyNet**](https://aclweb.org/anthology/P16-1154), which can preserve some of the text on the source side when translating.
