### ISSUE TITLE
Neural Machine Translation in Linear Time

### ISSUE THREAD

**Issue by alphadl** [THUNLP-MT/MT-Reading-List#42]
*  arxiv(cs.cl) 2016
* PDF link: https://arxiv.org/pdf/1610.10099v1.pdf
* MT & Language Modeling, this paper introduced 'ByteNet', a character level dilated conv NN based encoder-decoder model, which encouraged a line of research (e.g., Transformer) and  achieved two inspiring and insightful results in that time:  
```
* The ByteNet decoder attains state-of-the-art performance on character-level 
language modelling and outperforms the previous best results obtained with 
recurrent neural networks. 

* The ByteNet also achieves performance on raw character-level machine 
translation that approaches that of the best neural translation models that 
run in quadratic time.
```

**Comment by minicheshire** [comment]
Oh yes! ByteNet is also one of the baselines for Transformer. Thanks for recommendation!
