### ISSUE TITLE
Dynamic past and future for neural machine translation

### ISSUE THREAD

**Issue by zhengzx-nlp** [THUNLP-MT/MT-Reading-List#49]
Hi there! I open this issue to suggest this EMNLP'19 paper [Dynamic past and future for neural machine translation](https://www.aclweb.org/anthology/D19-1086/), which proposes a guided dynamic routing mechanism upon capsule networks to distinguish translated and untranslated contents during translation.

Thx!
zaixiang

**Comment by minicheshire** [comment]
Hi! Thanks for recommendation, and I've added the paper to the list~

**Comment by zhengzx-nlp** [comment]
@minicheshire thank you very much! I feel like it'd better be also put in "coverage constraint" due to its motivation. Sorry for not mentioning that.

**Comment by minicheshire** [comment]
Got it! Sorry for late reply. Will address it!
