### ISSUE TITLE
Learning Source Phrase Representations for Neural Machine Translation

### ISSUE THREAD

**Issue by salvation-z** [THUNLP-MT/MT-Reading-List#51]
Actually the link provided for this paper is wrong, and here is the correct link:
https://www.aclweb.org/anthology/2020.acl-main.37.pdf

**Comment by anoidgit** [comment]
@salvation-z that is really cool of you to find the paper before it is announced in the ACL anthology.
Thank you for your attention :)

**Comment by minicheshire** [comment]
Thank you for pointing out! I've corrected this one :)
