### ISSUE TITLE
[Document-level translation]Towards making the most of context in neural machine translaiton

### ISSUE THREAD

**Issue by zhengzx-nlp** [THUNLP-MT/MT-Reading-List#52]
Hi there,

Here is another paper about document-level translation (which can also deal with single-sentence translation):

Zaixiang Zheng, Xiang Yue, Shujian Huang, Jiajun Chen, Alexandra Birch. 2020. Towards Making the Most of Context in Neural Machine Translation. In Proceedings of the Twenty-Ninth International Joint Conference on Artificial Intelligence (IJCAI).

[ijcai version](https://www.ijcai.org/Proceedings/2020/0551.pdf) | [arxiv version (code available)](https://arxiv.org/abs/2002.07982)

Many thanks!
Zaixiang

**Comment by xc-kiwiberry** [comment]
Dear Zaixiang, 

We have added this paper to our list. Thanks for your suggestions.

Best wishes,
Xuancheng Huang

**Comment by zhengzx-nlp** [comment]
Thank you!

zaixiang
