### ISSUE TITLE
Mixture Models for Diverse Machine Translation Tricks of the Trade

### ISSUE THREAD

**Issue by PolarLion** [THUNLP-MT/MT-Reading-List#53]
### Fairness and  Diversity

Tianxiao Shen, Myle Ott, Michael Auli, Marc'Aurelio Ranzato:
Mixture Models for Diverse Machine Translation: Tricks of the Trade. ICML 2019: 5719-5728

http://proceedings.mlr.press/v97/shen19c.html

**Comment by minicheshire** [comment]
Thanks! But it's already in the Fairness and Diversity subsection :)
